[2025-03-26T11:08:56.664+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T11:08:56.685+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.sixth_task scheduled__2025-03-25T00:00:00+00:00 [queued]>
[2025-03-26T11:08:56.695+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.sixth_task scheduled__2025-03-25T00:00:00+00:00 [queued]>
[2025-03-26T11:08:56.696+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-26T11:08:56.709+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): sixth_task> on 2025-03-25 00:00:00+00:00
[2025-03-26T11:08:56.715+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T11:08:56.717+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2025-03-26T11:08:56.717+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'sixth_task', 'scheduled__2025-03-25T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpzb1oh7_s']
[2025-03-26T11:08:56.718+0000] {standard_task_runner.py:105} INFO - Job 81: Subtask sixth_task
[2025-03-26T11:08:56.760+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.sixth_task scheduled__2025-03-25T00:00:00+00:00 [running]> on host 7769c9b87de6
[2025-03-26T11:08:56.837+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='sixth_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-25T00:00:00+00:00'
[2025-03-26T11:08:56.838+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T11:08:56.851+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-26T11:08:56.852+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my sixth task']
[2025-03-26T11:08:56.861+0000] {subprocess.py:99} INFO - Output:
[2025-03-26T11:08:56.862+0000] {subprocess.py:106} INFO - hello world, this is my sixth task
[2025-03-26T11:08:56.863+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-26T11:08:56.884+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T11:08:56.885+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=sixth_task, run_id=scheduled__2025-03-25T00:00:00+00:00, execution_date=20250325T000000, start_date=20250326T110856, end_date=20250326T110856
[2025-03-26T11:08:56.933+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T11:08:56.980+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T11:08:56.984+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
