[2025-03-26T12:58:45.443+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T12:58:45.504+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.third_task manual__2025-03-26T12:58:38.282203+00:00 [queued]>
[2025-03-26T12:58:45.523+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.third_task manual__2025-03-26T12:58:38.282203+00:00 [queued]>
[2025-03-26T12:58:45.523+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-26T12:58:45.554+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-03-26 12:58:38.282203+00:00
[2025-03-26T12:58:45.562+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=804) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T12:58:45.566+0000] {standard_task_runner.py:72} INFO - Started process 808 to run task
[2025-03-26T12:58:45.565+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'third_task', 'manual__2025-03-26T12:58:38.282203+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpju31n9zx']
[2025-03-26T12:58:45.567+0000] {standard_task_runner.py:105} INFO - Job 94: Subtask third_task
[2025-03-26T12:58:45.622+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.third_task manual__2025-03-26T12:58:38.282203+00:00 [running]> on host 47640f2fe495
[2025-03-26T12:58:45.731+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T12:58:38.282203+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T12:58:38.282203+00:00'
[2025-03-26T12:58:45.733+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T12:58:45.772+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-26T12:58:45.775+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my third task']
[2025-03-26T12:58:45.789+0000] {subprocess.py:99} INFO - Output:
[2025-03-26T12:58:45.791+0000] {subprocess.py:106} INFO - hello world, this is my third task
[2025-03-26T12:58:45.793+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-26T12:58:45.826+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T12:58:45.826+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=third_task, run_id=manual__2025-03-26T12:58:38.282203+00:00, execution_date=20250326T125838, start_date=20250326T125845, end_date=20250326T125845
[2025-03-26T12:58:45.879+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T12:58:45.915+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T12:58:45.919+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
