[2025-03-24T13:29:12.796+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T13:29:12.825+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.zero_task manual__2025-03-24T13:29:08.094219+00:00 [queued]>
[2025-03-24T13:29:12.839+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.zero_task manual__2025-03-24T13:29:08.094219+00:00 [queued]>
[2025-03-24T13:29:12.840+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T13:29:12.858+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): zero_task> on 2025-03-24 13:29:08.094219+00:00
[2025-03-24T13:29:12.868+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'zero_task', 'manual__2025-03-24T13:29:08.094219+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpu4r_l7jz']
[2025-03-24T13:29:12.865+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=142) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T13:29:12.875+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask zero_task
[2025-03-24T13:29:12.876+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2025-03-24T13:29:13.029+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.zero_task manual__2025-03-24T13:29:08.094219+00:00 [running]> on host 7769c9b87de6
[2025-03-24T13:29:13.327+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='zero_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T13:29:08.094219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T13:29:08.094219+00:00'
[2025-03-24T13:29:13.329+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T13:29:13.390+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T13:29:13.392+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my zero task']
[2025-03-24T13:29:13.403+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T13:29:13.413+0000] {subprocess.py:106} INFO - hello world, this is my zero task
[2025-03-24T13:29:13.413+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T13:29:13.442+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T13:29:13.443+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=zero_task, run_id=manual__2025-03-24T13:29:08.094219+00:00, execution_date=20250324T132908, start_date=20250324T132912, end_date=20250324T132913
[2025-03-24T13:29:13.513+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T13:29:13.549+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T13:29:13.553+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
