[2025-03-25T07:43:17.006+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T07:43:17.036+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.fifth_task scheduled__2025-03-24T00:00:00+00:00 [queued]>
[2025-03-25T07:43:17.049+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.fifth_task scheduled__2025-03-24T00:00:00+00:00 [queued]>
[2025-03-25T07:43:17.049+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-25T07:43:17.067+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): fifth_task> on 2025-03-24 00:00:00+00:00
[2025-03-25T07:43:17.101+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1230) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T07:43:17.105+0000] {standard_task_runner.py:72} INFO - Started process 1233 to run task
[2025-03-25T07:43:17.107+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'fifth_task', 'scheduled__2025-03-24T00:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp8rqmsrl2']
[2025-03-25T07:43:17.109+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask fifth_task
[2025-03-25T07:43:17.241+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.fifth_task scheduled__2025-03-24T00:00:00+00:00 [running]> on host 7769c9b87de6
[2025-03-25T07:43:17.348+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='fifth_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-24T00:00:00+00:00'
[2025-03-25T07:43:17.349+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T07:43:17.374+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-25T07:43:17.376+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my fifth task']
[2025-03-25T07:43:17.390+0000] {subprocess.py:99} INFO - Output:
[2025-03-25T07:43:17.392+0000] {subprocess.py:106} INFO - hello world, this is my fifth task
[2025-03-25T07:43:17.393+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-25T07:43:17.421+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T07:43:17.422+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=fifth_task, run_id=scheduled__2025-03-24T00:00:00+00:00, execution_date=20250324T000000, start_date=20250325T074317, end_date=20250325T074317
[2025-03-25T07:43:17.500+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-25T07:43:17.523+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T07:43:17.526+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
