[2025-03-27T15:35:27.748+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T15:35:27.773+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.sixth_task manual__2025-03-27T15:35:19.927988+00:00 [queued]>
[2025-03-27T15:35:27.786+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.sixth_task manual__2025-03-27T15:35:19.927988+00:00 [queued]>
[2025-03-27T15:35:27.786+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-27T15:35:27.801+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): sixth_task> on 2025-03-27 15:35:19.927988+00:00
[2025-03-27T15:35:27.807+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=366) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T15:35:27.809+0000] {standard_task_runner.py:72} INFO - Started process 367 to run task
[2025-03-27T15:35:27.809+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'sixth_task', 'manual__2025-03-27T15:35:19.927988+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp_4ti6hjq']
[2025-03-27T15:35:27.811+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask sixth_task
[2025-03-27T15:35:27.859+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.sixth_task manual__2025-03-27T15:35:19.927988+00:00 [running]> on host 2a584310a0bb
[2025-03-27T15:35:27.947+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='sixth_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T15:35:19.927988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T15:35:19.927988+00:00'
[2025-03-27T15:35:27.948+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T15:35:27.962+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-27T15:35:27.964+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my sixth task']
[2025-03-27T15:35:27.976+0000] {subprocess.py:99} INFO - Output:
[2025-03-27T15:35:27.977+0000] {subprocess.py:106} INFO - hello world, this is my sixth task
[2025-03-27T15:35:27.978+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-27T15:35:28.001+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T15:35:28.002+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=sixth_task, run_id=manual__2025-03-27T15:35:19.927988+00:00, execution_date=20250327T153519, start_date=20250327T153527, end_date=20250327T153528
[2025-03-27T15:35:28.065+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T15:35:28.088+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T15:35:28.090+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
