[2025-03-24T13:29:17.139+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T13:29:17.170+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.third_task manual__2025-03-24T13:29:08.094219+00:00 [queued]>
[2025-03-24T13:29:17.185+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.third_task manual__2025-03-24T13:29:08.094219+00:00 [queued]>
[2025-03-24T13:29:17.185+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T13:29:17.204+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-03-24 13:29:08.094219+00:00
[2025-03-24T13:29:17.212+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T13:29:17.214+0000] {standard_task_runner.py:72} INFO - Started process 155 to run task
[2025-03-24T13:29:17.215+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'third_task', 'manual__2025-03-24T13:29:08.094219+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmppu8tsdf7']
[2025-03-24T13:29:17.216+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask third_task
[2025-03-24T13:29:17.273+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.third_task manual__2025-03-24T13:29:08.094219+00:00 [running]> on host 7769c9b87de6
[2025-03-24T13:29:17.374+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T13:29:08.094219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T13:29:08.094219+00:00'
[2025-03-24T13:29:17.376+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T13:29:17.395+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T13:29:17.397+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my third task']
[2025-03-24T13:29:17.408+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T13:29:17.410+0000] {subprocess.py:106} INFO - hello world, this is my third task
[2025-03-24T13:29:17.410+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T13:29:17.439+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T13:29:17.440+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=third_task, run_id=manual__2025-03-24T13:29:08.094219+00:00, execution_date=20250324T132908, start_date=20250324T132917, end_date=20250324T132917
[2025-03-24T13:29:17.485+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T13:29:17.495+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
