[2025-03-24T13:21:36.924+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T13:21:36.990+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-03-20T00:00:00+00:00 [queued]>
[2025-03-24T13:21:37.025+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.third_task scheduled__2025-03-20T00:00:00+00:00 [queued]>
[2025-03-24T13:21:37.028+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T13:21:37.070+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): third_task> on 2025-03-20 00:00:00+00:00
[2025-03-24T13:21:37.098+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=397) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T13:21:37.104+0000] {standard_task_runner.py:72} INFO - Started process 410 to run task
[2025-03-24T13:21:37.115+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'third_task', 'scheduled__2025-03-20T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpjcyl4g58']
[2025-03-24T13:21:37.119+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask third_task
[2025-03-24T13:21:37.422+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.third_task scheduled__2025-03-20T00:00:00+00:00 [running]> on host e1537a8d388b
[2025-03-24T13:21:37.905+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-20T00:00:00+00:00'
[2025-03-24T13:21:37.916+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T13:21:38.005+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T13:21:38.016+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my third task']
[2025-03-24T13:21:38.078+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T13:21:38.080+0000] {subprocess.py:106} INFO - hello world, this is my third task
[2025-03-24T13:21:38.082+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T13:21:38.175+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T13:21:38.177+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=third_task, run_id=scheduled__2025-03-20T00:00:00+00:00, execution_date=20250320T000000, start_date=20250324T132136, end_date=20250324T132138
[2025-03-24T13:21:38.353+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T13:21:38.451+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T13:21:38.456+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
