[2025-04-02T11:48:50.279+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-02T11:48:50.300+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-02T11:48:50.309+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-02T11:48:50.310+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-02T11:48:50.391+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-04-01 00:00:00+00:00
[2025-04-02T11:48:50.403+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=190) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-02T11:48:50.405+0000] {standard_task_runner.py:72} INFO - Started process 200 to run task
[2025-04-02T11:48:50.405+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmppx_ktu6p']
[2025-04-02T11:48:50.407+0000] {standard_task_runner.py:105} INFO - Job 194: Subtask second_task
[2025-04-02T11:48:51.096+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task scheduled__2025-04-01T00:00:00+00:00 [running]> on host d7b554d6843c
[2025-04-02T11:48:51.259+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-02T11:48:51.260+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-02T11:48:51.275+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-02T11:48:52.250+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my second task']
[2025-04-02T11:48:52.708+0000] {subprocess.py:99} INFO - Output:
[2025-04-02T11:48:52.710+0000] {subprocess.py:106} INFO - hello world, this is my second task
[2025-04-02T11:48:52.710+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-02T11:48:52.859+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-02T11:48:52.860+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250402T114850, end_date=20250402T114852
[2025-04-02T11:48:53.830+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-02T11:48:53.858+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-02T11:48:54.013+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
