[2025-03-28T11:18:11.949+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T11:18:11.993+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.fourth_task scheduled__2025-03-27T00:00:00+00:00 [queued]>
[2025-03-28T11:18:12.017+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.fourth_task scheduled__2025-03-27T00:00:00+00:00 [queued]>
[2025-03-28T11:18:12.018+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-28T11:18:12.044+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): fourth_task> on 2025-03-27 00:00:00+00:00
[2025-03-28T11:18:12.052+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-28T11:18:12.056+0000] {standard_task_runner.py:72} INFO - Started process 109 to run task
[2025-03-28T11:18:12.056+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'fourth_task', 'scheduled__2025-03-27T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpyy9zqvhx']
[2025-03-28T11:18:12.058+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask fourth_task
[2025-03-28T11:18:12.132+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.fourth_task scheduled__2025-03-27T00:00:00+00:00 [running]> on host 1041ed642999
[2025-03-28T11:18:12.277+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='fourth_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T00:00:00+00:00'
[2025-03-28T11:18:12.278+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-28T11:18:12.304+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-28T11:18:12.306+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my fourth task']
[2025-03-28T11:18:12.326+0000] {subprocess.py:99} INFO - Output:
[2025-03-28T11:18:12.329+0000] {subprocess.py:106} INFO - hello world, this is my fourth task
[2025-03-28T11:18:12.329+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-28T11:18:12.365+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-28T11:18:12.365+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=fourth_task, run_id=scheduled__2025-03-27T00:00:00+00:00, execution_date=20250327T000000, start_date=20250328T111811, end_date=20250328T111812
[2025-03-28T11:18:12.433+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-28T11:18:12.441+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
