[2025-04-02T11:48:41.329+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-02T11:48:41.484+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_3.first_task scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-02T11:48:41.492+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_3.first_task scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-02T11:48:41.492+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-02T11:48:41.507+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-04-01 00:00:00+00:00
[2025-04-02T11:48:41.635+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=178) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-02T11:48:41.638+0000] {standard_task_runner.py:72} INFO - Started process 180 to run task
[2025-04-02T11:48:41.638+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_3', 'first_task', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/seconddag.py', '--cfg-path', '/tmp/tmp3a5dgcxh']
[2025-04-02T11:48:41.640+0000] {standard_task_runner.py:105} INFO - Job 192: Subtask first_task
[2025-04-02T11:48:42.070+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_3.first_task scheduled__2025-04-01T00:00:00+00:00 [running]> on host d7b554d6843c
[2025-04-02T11:48:42.160+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='our_first_dag_3' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-02T11:48:42.161+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-02T11:48:42.195+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-02T11:48:42.197+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'hello this first task'"]
[2025-04-02T11:48:42.212+0000] {subprocess.py:99} INFO - Output:
[2025-04-02T11:48:42.213+0000] {subprocess.py:106} INFO - hello this first task
[2025-04-02T11:48:42.214+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-02T11:48:42.238+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-02T11:48:42.239+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_3, task_id=first_task, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250402T114841, end_date=20250402T114842
[2025-04-02T11:48:42.328+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-02T11:48:42.343+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T11:48:42.345+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
