[2025-03-25T07:43:16.818+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T07:43:16.844+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.fourth_task scheduled__2025-03-24T00:00:00+00:00 [queued]>
[2025-03-25T07:43:16.866+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.fourth_task scheduled__2025-03-24T00:00:00+00:00 [queued]>
[2025-03-25T07:43:16.867+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-25T07:43:16.896+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): fourth_task> on 2025-03-24 00:00:00+00:00
[2025-03-25T07:43:16.905+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1229) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T07:43:16.907+0000] {standard_task_runner.py:72} INFO - Started process 1231 to run task
[2025-03-25T07:43:16.908+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'fourth_task', 'scheduled__2025-03-24T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpm60q9ain']
[2025-03-25T07:43:16.909+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask fourth_task
[2025-03-25T07:43:16.998+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.fourth_task scheduled__2025-03-24T00:00:00+00:00 [running]> on host 7769c9b87de6
[2025-03-25T07:43:17.112+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='fourth_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-24T00:00:00+00:00'
[2025-03-25T07:43:17.114+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T07:43:17.144+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-25T07:43:17.145+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my fourth task']
[2025-03-25T07:43:17.167+0000] {subprocess.py:99} INFO - Output:
[2025-03-25T07:43:17.170+0000] {subprocess.py:106} INFO - hello world, this is my fourth task
[2025-03-25T07:43:17.171+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-25T07:43:17.214+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T07:43:17.215+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=fourth_task, run_id=scheduled__2025-03-24T00:00:00+00:00, execution_date=20250324T000000, start_date=20250325T074316, end_date=20250325T074317
[2025-03-25T07:43:17.293+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-25T07:43:17.325+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T07:43:17.327+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
