[2025-03-26T12:58:44.896+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T12:58:44.921+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.second_task manual__2025-03-26T12:58:38.282203+00:00 [queued]>
[2025-03-26T12:58:44.932+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.second_task manual__2025-03-26T12:58:38.282203+00:00 [queued]>
[2025-03-26T12:58:44.934+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-26T12:58:45.042+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): second_task> on 2025-03-26 12:58:38.282203+00:00
[2025-03-26T12:58:45.052+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=803) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T12:58:45.054+0000] {standard_task_runner.py:72} INFO - Started process 805 to run task
[2025-03-26T12:58:45.055+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'second_task', 'manual__2025-03-26T12:58:38.282203+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpr6yvuiqk']
[2025-03-26T12:58:45.056+0000] {standard_task_runner.py:105} INFO - Job 93: Subtask second_task
[2025-03-26T12:58:45.123+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.second_task manual__2025-03-26T12:58:38.282203+00:00 [running]> on host 47640f2fe495
[2025-03-26T12:58:45.237+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T12:58:38.282203+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T12:58:38.282203+00:00'
[2025-03-26T12:58:45.238+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T12:58:45.273+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-26T12:58:45.275+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my second task']
[2025-03-26T12:58:45.293+0000] {subprocess.py:99} INFO - Output:
[2025-03-26T12:58:45.337+0000] {subprocess.py:106} INFO - hello world, this is my second task
[2025-03-26T12:58:45.339+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-26T12:58:45.371+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T12:58:45.372+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=second_task, run_id=manual__2025-03-26T12:58:38.282203+00:00, execution_date=20250326T125838, start_date=20250326T125844, end_date=20250326T125845
[2025-03-26T12:58:45.430+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T12:58:45.462+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-26T12:58:45.464+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
