[2025-03-27T15:35:24.071+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T15:35:24.097+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.fifth_task manual__2025-03-27T15:35:19.927988+00:00 [queued]>
[2025-03-27T15:35:24.108+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.fifth_task manual__2025-03-27T15:35:19.927988+00:00 [queued]>
[2025-03-27T15:35:24.109+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-27T15:35:24.126+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): fifth_task> on 2025-03-27 15:35:19.927988+00:00
[2025-03-27T15:35:24.133+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=355) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T15:35:24.135+0000] {standard_task_runner.py:72} INFO - Started process 358 to run task
[2025-03-27T15:35:24.135+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'fifth_task', 'manual__2025-03-27T15:35:19.927988+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpsj_sc3ev']
[2025-03-27T15:35:24.137+0000] {standard_task_runner.py:105} INFO - Job 117: Subtask fifth_task
[2025-03-27T15:35:24.193+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.fifth_task manual__2025-03-27T15:35:19.927988+00:00 [running]> on host 2a584310a0bb
[2025-03-27T15:35:24.294+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='fifth_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T15:35:19.927988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T15:35:19.927988+00:00'
[2025-03-27T15:35:24.295+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T15:35:24.314+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-27T15:35:24.316+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is my fifth task']
[2025-03-27T15:35:24.328+0000] {subprocess.py:99} INFO - Output:
[2025-03-27T15:35:24.329+0000] {subprocess.py:106} INFO - hello world, this is my fifth task
[2025-03-27T15:35:24.330+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-27T15:35:24.354+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T15:35:24.355+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=fifth_task, run_id=manual__2025-03-27T15:35:19.927988+00:00, execution_date=20250327T153519, start_date=20250327T153524, end_date=20250327T153524
[2025-03-27T15:35:24.408+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T15:35:24.416+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
